### ISSUE TITLE
Error on loading a dxf

### ISSUE THREAD

**Issue by ma15569** [openjump-gis/dxf-driver#1]
This is the error I recived. It seems connected to JTS

java.lang.NoSuchMethodError: org.locationtech.jts.geom.CoordinateList.add(Lorg/locationtech/jts/geom/Coordinate;)Z
	at fr.michaelm.jump.drivers.dxf.DxfVERTEX.readEntity(DxfVERTEX.java:59)
	at fr.michaelm.jump.drivers.dxf.DxfPOLYLINE.readEntity(DxfPOLYLINE.java:79)
	at fr.michaelm.jump.drivers.dxf.DxfENTITIES.readEntities(DxfENTITIES.java:71)
	at fr.michaelm.jump.drivers.dxf.DxfFile.createFromFile(DxfFile.java:150)
	at fr.michaelm.jump.drivers.dxf.DxfFile.createFromFile(DxfFile.java:121)
	at fr.michaelm.jump.drivers.dxf.DxfReader.read(DxfReader.java:83)
	at com.vividsolutions.jump.io.datasource.ReaderWriterFileDataSource$1.executeQuery(ReaderWriterFileDataSource.java:108)
	at org.openjump.core.ui.io.file.DataSourceFileLayerLoader.process(DataSourceFileLayerLoader.java:175)
	at org.openjump.core.ui.io.file.DataSourceFileLayerLoader.open(DataSourceFileLayerLoader.java:280)
	at org.openjump.core.ui.plugin.file.open.OpenFileWizard.run(OpenFileWizard.java:164)
	at org.openjump.core.ui.plugin.file.OpenWizardPlugIn.run(OpenWizardPlugIn.java:106)
	at com.vividsolutions.jump.workbench.ui.task.TaskMonitorManager$TaskWrapper.run(TaskMonitorManager.java:151)

I attached the dxf file 

[295110_1993.zip](https://github.com/openjump-gis/dxf-driver/files/10075848/295110_1993.zip)

**Comment by mukoki** [comment]
Does it happen with 2.0.1 ? It looks like something I have fixed a few week ago : 
https://github.com/openjump-gis/dxf-driver/commit/c41af33da52d98af368f6bf6cd7f8319a8bb707a

**Comment by ma15569** [comment]
Hi Michael,  yuo are right! It works with OpenJUMP-Portable-20221116-r5178.
I wa using a previous version (5145).
